var tree = [["League",,"",
                [["FactoryMuffin","League\/FactoryMuffin.html","",
                [["Exceptions","League\/FactoryMuffin\/Exceptions.html","",
                [["DeleteFailedException","League\/FactoryMuffin\/Exceptions\/DeleteFailedException.html"," < ModelException",
                [        ]],["DeleteMethodNotFoundException","League\/FactoryMuffin\/Exceptions\/DeleteMethodNotFoundException.html"," < MethodNotFoundException",
                [        ]],["DeletingFailedException","League\/FactoryMuffin\/Exceptions\/DeletingFailedException.html"," < Exception",
                [        ]],["DirectoryNotFoundException","League\/FactoryMuffin\/Exceptions\/DirectoryNotFoundException.html"," < Exception",
                [        ]],["MethodNotFoundException","League\/FactoryMuffin\/Exceptions\/MethodNotFoundException.html"," < ModelException",
                [        ]],["ModelException","League\/FactoryMuffin\/Exceptions\/ModelException.html"," < Exception",
                [        ]],["NoDefinedFactoryException","League\/FactoryMuffin\/Exceptions\/NoDefinedFactoryException.html"," < ModelException",
                [        ]],["SaveFailedException","League\/FactoryMuffin\/Exceptions\/SaveFailedException.html"," < ModelException",
                [        ]],["SaveMethodNotFoundException","League\/FactoryMuffin\/Exceptions\/SaveMethodNotFoundException.html"," < MethodNotFoundException",
                [        ]]        ]],["Generators","League\/FactoryMuffin\/Generators.html","",
                [["Base","League\/FactoryMuffin\/Generators\/Base.html","",
                [        ]],["Call","League\/FactoryMuffin\/Generators\/Call.html"," < Base",
                [        ]],["Closure","League\/FactoryMuffin\/Generators\/Closure.html"," < Base",
                [        ]],["Factory","League\/FactoryMuffin\/Generators\/Factory.html"," < Base",
                [        ]],["Generic","League\/FactoryMuffin\/Generators\/Generic.html"," < Base",
                [        ]]        ]],["Facade","League\/FactoryMuffin\/Facade.html","",
                [        ]],["Factory","League\/FactoryMuffin\/Factory.html","",
                [        ]]        ]]        ]]        ]

